/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Quake II)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800861A4u
#define func_800861A4 BootEntry  /* alias */
